### ISSUE TITLE
Cocoapods Podspecs File?

### ISSUE THREAD

**Issue by AdiAyyakad** [Flight-School/AnyCodable#1]
Hey!

This framework looks great! I'd love to pull it into my project, but currently I use Cocoapods. Is that on your roadmap because I'd love to pull it in through that.

Thanks,
Adi

cc: @mattt

**Comment by dulingkang** [comment]
https://github.com/Flight-School/AnyCodable/pull/3

**Comment by AdiAyyakad** [comment]
Awesome thanks!

**Comment by mattt** [comment]
Following up on this: AnyCodable is now available via CocoaPods. Please see the `README` for installation instructions.
