### ISSUE TITLE
AnyCodable will crash when using JSONSerialization

### ISSUE THREAD

**Issue by Fidetro** [Flight-School/AnyCodable#10]
```
        var array = [AnyCodable]()
        array.append("test")
        do{
            try JSONSerialization.data(withJSONObject: array, options: .prettyPrinted)
        }catch{}
```
log:
```
failed: caught "NSInvalidArgumentException", "Invalid type in JSON write (_SwiftValue)"
```
Is there any way  can support JSONSerialization?

**Comment by mattt** [comment]
Related to #7.

**Comment by mattt** [comment]
AnyCodable isn't intended to be used directly via `JSONSerialization`. According to the [documentation of `data(withJSONObject:options:)`](https://developer.apple.com/documentation/foundation/jsonserialization/1413636-data):

> If obj will not produce valid JSON, an exception is thrown. This exception is thrown prior to parsing and represents a programming error, not an internal error. You should check whether the input will produce valid JSON before calling this method by using isValidJSONObject(_:).

```swift
var array = [AnyCodable]()
array.append("test")
JSONSerialization.isValidJSONObject(array) // false
```

If you want to encode a JSON string with an `AnyCodable` type, use `JSONEncoder`.
