### ISSUE TITLE
Embed in Swift?

### ISSUE THREAD

**Issue by cianiandreadev** [Flight-School/AnyCodable#11]
Simple question:

@mattt , why something like that cannot be embed on Swift itself? It's super handy. 
I bought your book anyway! Thanks for your amazing contributions :)

**Comment by mattt** [comment]
Hi @cianiandreadev. Thanks for the kind words and your support.

The decision of what goes into the Swift Standard Library is not mine to make. I can't speak for the maintainers, but my understanding is that there's a concern about encouraging incorrect use of Codable.
