### ISSUE TITLE
Try to set NSKeyedArchiver.archivedData

### ISSUE THREAD

**Issue by ShawnBaek** [Flight-School/AnyCodable#14]
Could you support to set AnyCodable Data into the NSKeyedArchiver?

```swift
let complexObject: [AnyCodable] = [["key": "value"], "string2", 1234, nil]

try! NSKeyedArchiver.archivedData(withRootObject: complexObject, requiringSecureCoding: false)
let data = try! NSKeyedUnarchiver.unarchiveTopLevelObjectWithData(complexObject)
.
.
```
But It didn't work..

**Comment by minacle** [comment]
`AnyCodable` is a swift-only type. If you want to pass an object to Objective-C, You can use non-generic Objective-C collections like `NSArray` or `NSDictionary`.

**Comment by mattt** [comment]
`AnyCodable` doesn't conform to `NSCoding` or `NSSecureCoding`, and cannot be used with `NSArchiver` or its subclasses. Like @minacle said, if you want to archive objects in this way, you first need to create Foundation / Objective-C-compatible types.
