### ISSUE TITLE
Error ITMS-90056: Info.plist file is missing the required key: CFBundleVersion

### ISSUE THREAD

**Issue by SaintNicholas** [Flight-School/AnyCodable#20]
I got an error while trying to submit to the app store with the AnyCodable framework included in my build. I got the error:

ERROR ITMS-90056: "This bundle Payload/MyApp.app/Frameworks/AnyCodable.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion. Please find more information about CFBundleVersion at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion"

In the AnyCodable_Info.plist I see the following:
  <key>CFBundleVersion</key>
  <string>$(CURRENT_PROJECT_VERSION)</string>

However, I don't see CURRENT_PROJECT_VERSION defined anywhere in the project.

**Comment by mattt** [comment]
@SaintNicholas How are you including AnyCodable into your project? CocoaPods? Carthage? Some other way?

**Comment by SaintNicholas** [comment]
@mattt Sorry, should have included more information.

We are using Carthage, with Xcode 10.2.1.

Our project has been successfully pushed to the App Store before, with a number of libraries (Alamofire, RxSwift, etc) included using this same method. This is the first time we've tried to push to the App Store with AnyCodable, and it's the first time we've ever seen this error.

**Comment by mattt** [comment]
I think this is caused by https://bugs.swift.org/browse/SR-4265. Nearly all the other projects I found on GitHub facing this problem also use Xcode projects generated by Swift Package Manager. Their solutions involved hard-coding `CURRENT_PROJECT_VERSION` to `1`, but I want to see if that's actually the best solution.

**Comment by SaintNicholas** [comment]
Ok thanks. I'll keep an eye on this issue.

**Comment by SaintNicholas** [comment]
Hey @mattt, did you find anything out? If you're not going to be able to, that's ok, I just need to find out what I'm going to do in my app to remove the AnyCodable dependency so I can push to Apple.

**Comment by SaintNicholas** [comment]
Thanks @mattt.

**Comment by mattt** [comment]
@SaintNicholas Thanks for your patience. I went ahead and cut a new 0.2.2 release that hard-codes `CURRENT_PROJECT_VERSION` to `1`, which should resolve your issue. Please let me know if you have any other problems related to that.

**Comment by danielsaidi** [comment]
Hi @mattt
I have the same problem in a library of mine. Did the hard coded current project version solve this issue for you?

**Comment by minacle** [comment]
Don't worry, @danielsaidi. It should work.
