### ISSUE TITLE
null being mapped to "\"null\"

### ISSUE THREAD

**Issue by jwboardman** [Flight-School/AnyCodable#29]
This mapping is resulting in the string "null" to be shown in our app as if it is a legal value, and forcing us to do a regex to replace "\"null\"" with "null" in the resulting JSON before sending it on to our app.

**Comment by jwboardman** [comment]
Weird - I only tried to edit the issue, not submit #30. Sorry about that.

**Comment by mattt** [comment]
Hi, @jwboardman. I think I need some more context to understand why this is happening. Can you please provide an example that demonstrates this behavior?

**Comment by jwboardman** [comment]
Ok, the data came from a remote site and it had "null" in it instead of null. AnyCodable is working correctly for this.

**Comment by mattt** [comment]
Thanks for the update, @jwboardman. Glad to hear you found a resolution.
