### ISSUE TITLE
Library Evolution Support

### ISSUE THREAD

**Issue by bradleysmaskell** [Flight-School/AnyCodable#36]
For frameworks that have `BUILD_LIBRARY_FOR_DISTRIBUTION=YES` we see the following warning when pulling in through SPM. 

<img width="708" alt="Screen Shot 2020-06-24 at 10 12 03 AM" src="https://user-images.githubusercontent.com/8466790/85572902-668e9980-b603-11ea-8a5a-50536613ed55.png">

@mattt would you be open to setting this to `YES`?

**Comment by mattt** [comment]
@bradleysmaskell Absolutely. If you send me a PR with the necessary changes, I'd be happy to merge that in an cut a new release.
