### ISSUE TITLE
AnyCodable 0.3.0 is not available via CocoaPods

### ISSUE THREAD

**Issue by lyamamot** [Flight-School/AnyCodable#39]
It looks like AnyCodable version 0.3.0 is not available via CocoaPods.

	[!] CocoaPods could not find compatible versions for pod "AnyCodable-FlightSchool":
	  In Podfile:
	    AnyCodable-FlightSchool (= 0.3.0)

	None of your spec sources contain a spec satisfying the dependency: `AnyCodable-FlightSchool (= 0.3.0)`.

	You have either:
	 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
	 * mistyped the name or version.
	 * not added the source repo that hosts the Podspec to your Podfile.

Perhaps this is because the CI build failed? https://github.com/Flight-School/AnyCodable/runs/887025181

**Comment by bnash2501** [comment]
Yup, saw the same issue. It looks like it's not published http://cocoapods.org/pods/AnyCodable-FlightSchool

**Comment by mattt** [comment]
Apologies for the late response, but this is now fixed. Going forward, all new versions will be automatically pushed to CocoaPods thanks to our new [release automation](https://github.com/Flight-School/AnyCodable/runs/1349444719).
