### ISSUE TITLE
Add tag

### ISSUE THREAD

**Issue by jkmathew** [Flight-School/AnyCodable#4]
Please add a tag- atlas 0.1.0. So that we can use with SPM

**Comment by yonaskolb** [comment]
For what it’s worth I’ve included AnyCodable in https://github.com/yonaskolb/Codability which is a library that contains a bunch of helpers when using Codable. It’s got some tagged releases as well.
Thanks for the book and the great approach @mattt!

**Comment by mattt** [comment]
@jkmathew I just pushed the tag 0.1.0, so you can use that with the Swift Package Manager.
