### ISSUE TITLE
Extension of internal protocol cannot be declared public error

### ISSUE THREAD

**Issue by catchakos** [Flight-School/AnyCodable#41]
I get this error while compiling with Xcode 12.0: 

/Pods/AnyCodable-FlightSchool/Sources/AnyCodable/AnyDecodable.swift:66:1: error: extension of internal protocol cannot be declared public
public extension _AnyDecodable {
^~~~~~~

and suggested Xcode fix:
"Remove public" 

The error seems to go away if I deintegrate the pods and install them again, but somehow resurfaces again after switching to a different build configuration 

Any ideas?

**Comment by catchakos** [comment]
Closing this, it was related to some new rule from a SwiftFormat pod update.

**Comment by mattt** [comment]
@catchakos Thanks for following up on this. Glad to hear that you were able to resolve this.
