### ISSUE TITLE
How to convert AnyCodable to Hashable

### ISSUE THREAD

**Issue by glve1027** [Flight-School/AnyCodable#45]
currently i have some data. This data is [String: AnyCodable], i just want to get this data's hashvalue. Because the value in this data is dynamic. It can be Number/String/Dictionary/Array/Other Object. How should I do？？

```swift
//???
extension AnyCodable: Hashable {
    
}
```

**Comment by minacle** [comment]
`AnyCodable` is not conforming `Hashable` so you can't perform it in current version `0.4.0`.
