### ISSUE TITLE
Strings only work when it's a literal? 

### ISSUE THREAD

**Issue by alexisbronchart** [Flight-School/AnyCodable#49]
I'm trying this and getting this error:
<img width="808" alt="Screenshot 2021-01-29 at 09 48 41" src="https://user-images.githubusercontent.com/1279527/106253133-639dfc00-6217-11eb-9ecc-ab345d4bb22d.png">
Is this a bug or does it work only with literals?

**Comment by mattt** [comment]
Your example constructs a dictionary with `String` keys and `AnyEncodable` values. Like the compiler error says, you can't put a `String` value where an `AnyEncodable` value is expected. The reason string literals work is that `AnyEncodable` `AnyEncodable` conforms to [`ExpressibleByStringLiteral`](https://developer.apple.com/documentation/swift/expressiblebystringliteral); in this context, string literals construct `AnyEncodable` values, not `String`.

You can convert a `String` to `AnyEncodable` using string interpolation (as you have in your example) or through an explicit initializer (`AnyEncodable(bar)`).
