### ISSUE TITLE
Cannot convert value of type '<Type>' to expected dictionary value type 'AnyEncodable'

### ISSUE THREAD

**Issue by RichMarketApp** [Flight-School/AnyCodable#52]
Hi,
I have a problem with assigning data to the dictionary that should be encodable. The Data struct inherit from Codable protocol and contains four different variable types. 

I am trying to convert this struct to dictionary that will represent some other model. Please find a dummy code below:
```
struct Data: Codable {
    let string: String
    let int: Int
    let double: Double
    let bool: Bool
}

let data: Data
var body: [String : AnyEncodable]? {
        [
            "string": data.string,
            "int": data.int,
            "double": data.double,
            "bool": data.bool
        ]
    }
```
    
When the project is compiling I am getting four errors:

> Cannot convert value of type 'String' to expected dictionary value type 'AnyEncodable'
> Cannot convert value of type 'Int' to expected dictionary value type 'AnyEncodable'
> Cannot convert value of type 'Double' to expected dictionary value type 'AnyEncodable'
> Cannot convert value of type 'Bool' to expected dictionary value type 'AnyEncodable'

Is there any simple way to fix it and left the code clean?

**Comment by minacle** [comment]
Quick solution: just wrap the values with `.init` like this

```swift
var body: [String: AnyEncodable]? =
    ["string": .init(data.string),
     "int": .init(data.int),
     "double": .init(data.double),
     "bool": .init(data.bool)]
```
