### ISSUE TITLE
How to encode object with AnyCodable

### ISSUE THREAD

**Issue by Steven4294** [Flight-School/AnyCodable#56]
I am using Vapor, though I don't believe that matters. I'm trying to pass in an object something that conforms to `AnyEncodable` See code:

```
let dic: [String: AnyEncodable] = [
    "number": 1,
    "string": "2020-10-01",
    "isBool": true,
    "post": Post(payload: "")
]
try req.content.encode(dic, as: .urlEncodedForm)
```

And my post object
```
struct Post {
    let payload: String
}
```
How do I make `Post` conform to `AnyEncodable`, so I can pass in an object as a value in my dictionary like such?

Additionally, I've tried:
```
KLPayload(
            token: "",
            time: 0,
            customer_properties: [
                "email": checkout.email
            ]
)

struct KLPayload: Encodable  {
    let token: String
    let time: Int
    let customer_properties: [String: AnyEncodable]
}
```
And I get `Cannot convert value of type 'String' to expected dictionary value type 'AnyEncodable'`

**Comment by minacle** [comment]
> How do I make `Post` conform to `AnyEncodable`, so I can pass in an object as a value in my dictionary like such?

Just mark your struct as _Encodable_.

```swift
struct Post: Encodable {
    let payload: String
}
```

---

> I get `Cannot convert value of type 'String' to expected dictionary value type 'AnyEncodable'`

Due to the type of `checkout.email` is _String_, you cannot insert it directly without wrapping with the _AnyEncodable_ initialiser.

```swift
KLPayload(
    token: "",
    time: 0,
    customer_properties: [
        "email": .init(checkout.email)
    ]
)

struct KLPayload: Encodable  {
    let token: String
    let time: Int
    let customer_properties: [String: AnyEncodable]
}
```
