### ISSUE TITLE
Release job failed

### ISSUE THREAD

**Issue by minacle** [Flight-School/AnyCodable#66]
[!] Authentication token is invalid or unverified. Either verify it with the email that was sent or register a new session.

https://github.com/Flight-School/AnyCodable/actions/runs/1961929014

[logs_47.zip](https://github.com/Flight-School/AnyCodable/files/8221518/logs_47.zip)

**Comment by mattt** [comment]
Updated the `COCOAPODS_TRUNK_TOKEN` secret with a fresh token and re-ran. Here's the successful run: https://github.com/Flight-School/AnyCodable/runs/5545229687?check_suite_focus=true

```
--------------------------------------------------------------------------------
 🎉  Congrats
 🚀  AnyCodable-FlightSchool (0.6.3) successfully published
 📅  March 14th, 22:09
 🌎  https://cocoapods.org/pods/AnyCodable-FlightSchool
 👍  Tell your friends!
--------------------------------------------------------------------------------
```
